import {useRef,useState} from 'react';
import {motion,useScroll,useTransform} from 'framer-motion';
import {ArrowDown,ArrowUpRight,BriefcaseBusiness,Check,ChevronRight,Clock3,Code2,Download,Globe2,GraduationCap,Mail,MapPin,Menu,MessageSquareQuote,Phone,ShieldCheck,Sparkles,X} from 'lucide-react';
import {SiReact,SiTypescript,SiJavascript,SiNextdotjs,SiNodedotjs,SiExpress,SiMongodb,SiMysql,SiTailwindcss,SiGit,SiGithub,SiVercel,SiGithubcopilot,SiAngular} from 'react-icons/si';
import businessImg from '@/assets/project-businessgenie.jpg';
import crmImg from '@/assets/project-crm.jpg';
import shopImg from '@/assets/Ecommerce.jpg';

const reveal={initial:{opacity:0,y:34},whileInView:{opacity:1,y:0},viewport:{once:true,margin:'-70px'},transition:{duration:.7,ease:[.22,1,.36,1] as [number,number,number,number]}};
const jobs=[
 {period:'Jan 2026 — Present',role:'MERN Stack Developer',company:'BusinessGenie',location:'Lahore, Pakistan',points:['Develop and maintain responsive, scalable applications with React, TypeScript, Node.js, Express and database integrations.','Build reusable components, dashboards, forms, authentication workflows and API-connected interfaces.','Apply AI-assisted engineering to requirements, planning, debugging, refactoring, reviews, testing and documentation.','Support accessibility, cross-browser compatibility, performance, Git workflows, deployment and CI/CD.']},
 {period:'Feb 2025 — Aug 2025',role:'MERN Stack Developer',company:'House of Perfection',location:'Lahore, Pakistan',points:['Engineered responsive React interfaces for desktop, tablet and mobile applications.','Integrated React interfaces with Node.js, Express and REST APIs for dependable client-server exchange.','Implemented MySQL, MongoDB, validation, CRUD and database-backed workflows.','Resolved layout, usability and data-flow issues through testing and iterative delivery.']},
 {period:'2024',role:'Web Developer',company:'GrowBusinessDigital / Independent Projects',location:'Remote / Lahore',points:['Built client-focused full-stack and frontend applications using React, Next.js, JavaScript and Node.js.','Developed authentication flows, user management, responsive content and reusable components.','Managed source control, deployment preparation, debugging and iterative enhancements.']},
 {period:'3 Months · 2024',role:'Sales & Marketing Executive',company:'Client Outreach & Business Development',location:'Lahore, Pakistan',points:['Managed lead generation, follow-ups and professional customer communication.','Presented services, handled enquiries and supported relationship management and conversion.']}
];
const projects=[
 {title:'BusinessGenie Consulting',type:'Corporate consulting platform',image:businessImg,accent:'#d9ff57',stack:['React.js','TypeScript','Responsive UI'],copy:'A corporate consulting experience presenting ERP implementation, HRMS automation, digital marketing, SEO and web development through clear, reusable service journeys.',challenge:'Turn a broad service catalogue into an easy-to-navigate business website.',result:'Reusable content architecture built for clarity, scalability and international presentation.'},
 {title:'CRM System',type:'Database-driven operations platform',image:crmImg,accent:'#88c7ff',stack:['React.js','Node.js','Express','MySQL / MongoDB'],copy:'CRM workflows for user management, organized records, authentication practice, form handling, validation, REST APIs and end-to-end CRUD operations.',challenge:'Organize users, records and daily operations in one dependable workflow.',result:'Structured CRUD flows, validation and API-connected interfaces for cleaner operations.'},
 {title:'StyleShop Express',type:'Responsive commerce interface',image:shopImg,accent:'#ffb894',stack:['React.js','JavaScript','Vercel'],copy:'A polished e-commerce frontend with reusable product components, intuitive browsing, interactive experiences and mobile-first behavior.',challenge:'Create a fast browsing experience that remains clear on smaller screens.',result:'Responsive product discovery with reusable components and deployment-ready structure.'}
];
const tech=[['React',SiReact],['TypeScript',SiTypescript],['JavaScript',SiJavascript],['Next.js',SiNextdotjs],['Angular',SiAngular],['Node.js',SiNodedotjs],['Express',SiExpress],['MongoDB',SiMongodb],['MySQL',SiMysql],['Tailwind CSS',SiTailwindcss],['Git',SiGit],['GitHub',SiGithub],['Vercel',SiVercel],['AI Engineering',SiGithubcopilot]];

function TiltCard({children,className=''}:{children:React.ReactNode,className?:string}){const ref=useRef<HTMLDivElement>(null);const move=(e:React.MouseEvent)=>{const el=ref.current;if(!el)return;const r=el.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;el.style.transform=`perspective(1100px) rotateX(${-y*7}deg) rotateY(${x*9}deg) translateY(-6px)`};return <div ref={ref} onMouseMove={move} onMouseLeave={()=>{if(ref.current)ref.current.style.transform='perspective(1100px) rotateX(0) rotateY(0)'}} className={`tilt ${className}`}>{children}</div>}
function Title({index,kicker,title}:{index:string,kicker:string,title:string}){return <motion.div {...reveal} className="section-title"><div><span>{index}</span><p>{kicker}</p></div><h2>{title}</h2></motion.div>}

export default function Index(){const [open,setOpen]=useState(false);const {scrollYProgress}=useScroll();const scaleX=useTransform(scrollYProgress,[0,1],[0,1]);return <main>
 <motion.div className="progress" style={{scaleX}}/>
 <header><a href="#top" className="logo"><img src="/ua-logo.png" alt="Usman Anwar logo"/><span>USMAN ANWAR<small>FULL-STACK ENGINEER</small></span></a><button className="menu" onClick={()=>setOpen(!open)} aria-label="Open navigation" aria-expanded={open}>{open?<X/>:<Menu/>}</button><nav className={open?'open':''}>{['About','Services','Work','Experience','Proof','Contact'].map(x=><a key={x} href={'#'+x.toLowerCase()} onClick={()=>setOpen(false)}>{x}</a>)}<a className="resume" href="/Usman-Anwar-CV.pdf" download>Resume <Download size={15}/></a></nav></header>
 <section id="top" className="hero shell">
  <div className="hero-copy"><motion.h1 initial={{opacity:0,y:35}} animate={{opacity:1,y:0}} transition={{delay:.18,duration:.8}}>From business idea to <em>production-ready</em> product.</motion.h1><motion.p initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.36}} className="hero-lead">I help companies design, build and improve responsive web applications—from precise React interfaces to dependable Node.js APIs, databases and deployment.</motion.p><motion.div initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} transition={{delay:.46}} className="actions"><a href="#work" className="primary">Explore case studies <ArrowDown size={17}/></a><a href="mailto:usmanali22181@gmail.com?subject=Project%20enquiry%20for%20Usman%20Anwar" className="secondary">Discuss a project <ArrowUpRight size={17}/></a></motion.div><div className="quick"><span><b>3+</b> Years combined experience</span><span><b>End-to-end</b> Frontend, API & database</span><span><b>Remote-ready</b> Clear async communication</span></div></div>
  <motion.div initial={{opacity:0,scale:.88,rotate:4}} animate={{opacity:1,scale:1,rotate:0}} transition={{delay:.25,duration:.9}} className="hero-visual"><div className="code-card"><div className="code-head"><span/><span/><span/><small>product-engineer.tsx</small></div><pre><code><b>const</b> engineer = {'{'}{`\n  `}focus: <i>'usable products'</i>,{`\n  `}stack: [<i>'React'</i>, <i>'Node'</i>],{`\n  `}quality: <i>'production-ready'</i>,{`\n  `}mindset: <i>'solve → ship → improve'</i>{`\n`}{'}'};</code></pre><div className="ship"><Check size={16}/> Build ready for review</div></div><div className="floating f1"><Code2/>Clean architecture</div><div className="floating f2"><Sparkles/>AI-assisted delivery</div><div className="ring r1"/><div className="ring r2"/></motion.div>
 </section>
 <section className="marquee"><div>{['React.js','TypeScript','Node.js','REST APIs','MongoDB','MySQL','Next.js','AI-assisted development','CI/CD','Responsive Engineering'].map(x=><span key={x}>{x}<i>✦</i></span>)}</div></section>
 <section id="about" className="shell pad"><Title index="01" kicker="Positioning" title="A product-minded developer for ambitious digital work."/><div className="about-grid"><motion.p {...reveal} className="statement">I turn business requirements into maintainable software with clear interfaces, structured data flows and a delivery process clients can trust.</motion.p><motion.div {...reveal} className="about-copy"><p>MERN Stack Developer and Full Stack Software Engineer with 3+ years of combined professional and project-based experience. My work covers the complete software development lifecycle: discovery, interface architecture, backend APIs, databases, testing, accessibility, optimization and deployment.</p><div className="value-row"><span><ShieldCheck/>Maintainable code</span><span><Clock3/>Reliable delivery</span><span><Globe2/>Global collaboration</span></div></motion.div></div></section>
 <section id="services" className="services pad"><div className="shell"><Title index="02" kicker="Capabilities" title="Everything needed to move a web product forward."/><div className="service-grid"><motion.article {...reveal}><Globe2/><span>01</span><h3>Frontend engineering</h3><p>Responsive interfaces, dashboards, navigation, search, forms and reusable design systems built for real users.</p><b>React · Next.js · TypeScript · Tailwind</b></motion.article><motion.article {...reveal}><Code2/><span>02</span><h3>Backend & API development</h3><p>REST APIs, middleware, validation, authentication concepts and dependable server-side business logic.</p><b>Node.js · Express · REST APIs</b></motion.article><motion.article {...reveal}><BriefcaseBusiness/><span>03</span><h3>Business applications</h3><p>Database-driven platforms, CRM workflows and internal tools shaped around daily operations.</p><b>MongoDB · MySQL · CRUD</b></motion.article><motion.article {...reveal}><Sparkles/><span>04</span><h3>Product improvement</h3><p>Debugging, refactoring, performance, accessibility and AI-assisted development with human review.</p><b>Testing · WCAG · CI/CD</b></motion.article></div></div></section>
 <section id="work" className="work pad"><div className="shell"><Title index="03" kicker="Selected work" title="Projects shaped around real business outcomes."/><div className="projects">{projects.map((p,i)=><motion.article {...reveal} key={p.title} className={i%2?'reverse':''} style={{'--accent':p.accent} as React.CSSProperties}><TiltCard className="project-media"><img src={p.image} alt={`${p.title} interface`}/><span>0{i+1}</span></TiltCard><div className="project-info"><p>{p.type}</p><h3>{p.title}</h3><div className="tags">{p.stack.map(s=><span key={s}>{s}</span>)}</div><p className="project-copy">{p.copy}</p><dl><div><dt>Challenge</dt><dd>{p.challenge}</dd></div><div><dt>Outcome</dt><dd>{p.result}</dd></div></dl><a href={`mailto:usmanali22181@gmail.com?subject=${encodeURIComponent('Walkthrough request: '+p.title)}`}>Request project walkthrough <ChevronRight/></a></div></motion.article>)}</div><motion.div {...reveal} className="more-work"><div><b>Additional delivery experience</b><p>Business Transformation Hub · AI-assisted engineering workflow · Developer portfolio</p></div><p>Work also covers modular React architecture, Tailwind interfaces, cross-browser testing, code review, deployment workflows and technical documentation.</p></motion.div></div></section>
 <section id="experience" className="shell pad"><Title index="04" kicker="Experience" title="Hands-on delivery across teams, products and clients."/><div className="timeline">{jobs.map((j,i)=><motion.article {...reveal} key={j.role+j.company}><div className="number">0{i+1}</div><div className="period">{j.period}<small>{j.location}</small></div><div className="role"><p>{j.company}</p><h3>{j.role}</h3><ul>{j.points.map(p=><li key={p}>{p}</li>)}</ul></div></motion.article>)}</div></section>
 <section id="stack" className="stack pad"><div className="shell"><Title index="05" kicker="Technology stack" title="Modern tools, used with engineering discipline."/><div className="tech-grid">{tech.map(([name,Icon],i)=><motion.div {...reveal} transition={{delay:(i%7)*.04}} className="tech" key={name as string}><Icon/><span>{name as string}</span></motion.div>)}</div><div className="stack-details"><article><span>Frontend</span><p>React Query · Redux · HTML5 · CSS3 · Bootstrap · Webpack · Responsive design</p></article><article><span>Engineering</span><p>Testing · Debugging · WCAG 2.2 · Performance · Cross-browser compatibility</p></article><article><span>Workflow</span><p>Agile · SDLC · Jira · Azure DevOps · CI/CD · Technical documentation</p></article></div></div></section>
 <section className="process pad"><div className="shell"><Title index="06" kicker="Delivery process" title="A clear flow from idea to production."/><div className="process-grid">{[['01','Discover','Clarify business goals, users, scope and technical requirements.'],['02','Design the system','Plan components, data flows, APIs, database logic and responsive states.'],['03','Build & integrate','Develop maintainable interfaces, services and end-to-end workflows.'],['04','Validate & ship','Test behavior, accessibility and performance before deployment.']].map((p,i)=><motion.article {...reveal} transition={{delay:i*.08}} key={p[0]}><span>{p[0]}</span><h3>{p[1]}</h3><p>{p[2]}</p></motion.article>)}</div></div></section>
 <section id="proof" className="proof pad"><div className="shell"><Title index="07" kicker="Trust & proof" title="Professional confidence without invented claims."/><div className="proof-grid"><motion.article {...reveal} className="proof-feature"><MessageSquareQuote/><p>Client reviews will be published here only with the client’s approval. Until then, project walkthroughs, code discussions and professional references are available on request.</p><a href="mailto:usmanali22181@gmail.com?subject=Reference%20request%20for%20Usman%20Anwar">Request a reference <ArrowUpRight/></a></motion.article><motion.div {...reveal} className="proof-points"><div><Check/><span><b>Transparent scope</b>Clear expectations before development begins.</span></div><div><Check/><span><b>Progress visibility</b>Concise updates and review-ready milestones.</span></div><div><Check/><span><b>Quality ownership</b>Responsive, maintainable and tested delivery.</span></div><div><Check/><span><b>Professional handoff</b>Organized source, documentation and deployment support.</span></div></motion.div></div></div></section>
 <section className="ai pad"><div className="shell ai-grid"><motion.div {...reveal}><p className="overline">AI-ASSISTED DEVELOPMENT</p><h2>Faster iteration.<br/><em>Human judgement.</em></h2><p>Generative AI supports my engineering workflow—not replaces it. I use ChatGPT, GitHub Copilot, Claude and Gemini for structured acceleration while reviewing every recommendation for quality, relevance and maintainability.</p></motion.div><motion.div {...reveal} className="ai-flow">{['Requirement analysis','Prompt engineering','Component planning','Debugging & refactoring','Code review support','Test-case planning','Documentation','AI API integration'].map((x,i)=><div key={x}><span>{String(i+1).padStart(2,'0')}</span>{x}<ArrowUpRight size={16}/></div>)}</motion.div></div></section>
 <section className="shell pad education"><Title index="08" kicker="Education & attributes" title="Built on continuous learning and ownership."/><div className="education-grid"><motion.article {...reveal}><GraduationCap/><p>In progress · Lahore, Pakistan</p><h3>Bachelor of Science in Information Technology</h3><b>Virtual University of Pakistan</b><span>Information technology, programming, software development, databases, web technologies and computing fundamentals.</span></motion.article><motion.article {...reveal}><GraduationCap/><p>2022 — 2024</p><h3>Intermediate in Computer Science</h3><b>Commerce College, Kamalia</b><span>Programming fundamentals, computer concepts and foundational software-development principles.</span></motion.article></div><div className="attributes">{['Problem Solving','Requirement Analysis','Team Collaboration','Continuous Learning','Delivery Ownership','Remote Collaboration'].map(x=><span key={x}>{x}</span>)}</div></section>
 <section id="contact" className="contact pad"><div className="shell contact-grid"><div><p className="overline">LET’S BUILD SOMETHING USEFUL</p><h2>Need a reliable full-stack partner?</h2><p>Available for full-time, remote and project-based opportunities with international teams and clients.</p><a className="contact-button" href="mailto:usmanali22181@gmail.com">Discuss your project <ArrowUpRight/></a></div><div className="contact-list"><a href="mailto:usmanali22181@gmail.com"><Mail/><span><small>Email</small>usmanali22181@gmail.com</span></a><a href="tel:+923710571295"><Phone/><span><small>Phone</small>+92 371 0571295</span></a><div><MapPin/><span><small>Location</small>Lahore, Pakistan · Open to remote</span></div><a href="#top"><ArrowUpRight/><span><small>Portfolio</small>Back to top</span></a></div></div></section>
 <footer><div className="shell"><a className="logo" href="#top"><img src="/ua-logo.png" alt="UA"/><span>USMAN ANWAR<small>FULL-STACK ENGINEER</small></span></a><p>© 2026 Usman Anwar. Engineered with intent.</p></div></footer>
 </main>}
